### ISSUE TITLE
Needs to handle multiple errors in testing

### ISSUE THREAD

**Issue by jekwatt** [hgsc-project-managers/ngsi-pm#17]
When a JSON key (for SE or merge) is replaced with a wrong key (camel case instead of snake case), this creates multiple errors.

The below failing tests are currently marked as 'xfail' for the reason 'expected to fail' and need to be updated.

@pytest.mark.xfail(reason="expected to fail", raises=AssertionError)

test_hgv19_se_ec5_unit

test_hgv19_se_ec2_unit

test_hgv19_merge_ec21_event_id_unit

test_hgv19_merge_ec21_library_name_unit

test_hgv19_merge_ec5_unit

**Comment by itsmarcy** [comment]
#19 addresses some of the failing test listed.

I have two concerns for two test that I mentioned in the PR but will put here as well:

- `test_hgv19_merge_ec21_event_id_unit` is still failing because there is no data in the expect.tsv
- `test_hgv19_merge_ec21_library_name_unit` is still failing. I was following the path and I do not see how `JSON has wrong keys` is raised. Line 337 in `mplx_qc.py` raises error_code 21 but does not pass the same message. The test is also changing the key `library_name`. Line 336 only checks for the key `id` so this issue wont even raise. I'm not sure if this is a bug in the code or a misunderstanding in the test.

So should `test_hgv19_merge_ec21_library_name_unit` check for the `JSON has wrong keys` (then the code itself should be edited) or since it's dealing with `library_name` just check for `key 'library_name' in Merge is missing` error (only test will need to be edited in this case)?

**Comment by itsmarcy** [comment]
PR #19 has been merged and branch `hgv19_testing` branch now handles multiple errors in testing.

The two concerns that raised have been created with their own two issues as instructed.

I recommend closing unless you all think otherwise.

**Comment by jekwatt** [comment]
Fixed by #19
